### ISSUE TITLE
Add CRC to Star Frame

### ISSUE THREAD

**Issue by nealian** [nealian/cse353_project3#3]
The CRC field should contain the sum of the byte values of the rest of the frame, truncated to one byte. This provides a checksum that a destination node can check to ensure that the data arrived intact. This will follow the data.

**Comment by nealian** [comment]
```
uint8_t crc = 0;
for byte_x in frame:
  crc += byte_x;
```

**Comment by nealian** [comment]
Remove frame priority, too

**Comment by 0culus** [comment]
We'll remove the frame priority as code cleanup at the end.

**Comment by 0culus** [comment]
See https://github.com/nealian/cse353_project3/tree/3-crc-ring-frame

**Comment by nealian** [comment]
Closed by #7
